### ISSUE TITLE
Dead humanoid mobs will be in a T-pose if you return to them before they despawn

### ISSUE THREAD

**Issue by pressure68** [MATTYOneInc/AionEncomBase#11]
I thought this issue had been fixed before, did the fix just not get transferred here?

**Comment by BeckUp-Media** [comment]
something with "void see" if i remember correct, S_PUT_NPC has some Stuff missing with the correct state.

**Comment by BeckUp-Media** [comment]
is it fixed here or can i help?

**Comment by MATTYOneInc** [comment]
https://github.com/MATTYOneInc/AionEncomBase/commit/ffd2f380b5d4338ec898fe4868112f85593b4354
