### ISSUE TITLE
(Information) Bug.

### ISSUE THREAD

**Issue by Romik110** [MATTYOneInc/AionEncomBase#12]
Personal Shop game crashes when using Bin64.
Bin32 works fine.

**Comment by pressure68** [comment]
This now works fine.

**Comment by Romik110** [comment]
I didn't see this fix. You launched two windows and did a bargain? Did you launch the client through bin64?

**Comment by Romik110** [comment]
> This now works fine.
I didn't see this fix. You launched two windows and did a bargain? Did you launch the client through bin64?
