### ISSUE TITLE
Developers Credits

### ISSUE THREAD

**Issue by Aion-Voidstar** [MATTYOneInc/AionEncomBase#14]
Most of your developers credits ar just fake. The most important developer group Aion-Core is not listed, which was the most
important developer group since Aion 4.6 Emulator.
Hier die original credits to AIon Emulator;
http://www.aion-core.net/emucredits.txt

**Comment by MATTYOneInc** [comment]
In the list, I indicated those developers whose nicknames were indicated in the source code files.

**Comment by Aion-Voidstar** [comment]
Okay, I understand.
