### ISSUE TITLE
Please delete this. Thank you!

### ISSUE THREAD

**Issue by ghost** [MATTYOneInc/AionEncomBase#18]

**Comment by benas80** [comment]
Its working ok (even wrong description), after Corrupt Ifrit killed you have to go to place where you start the instance and speak to the NPC (arrived after kill Fiery Sealing Stone at start of the instance).

**Comment by benas80** [comment]
Btw. Corrupted Ifrit have 4200000 HP! You can have some problem to kill him alone :)

**Comment by Topaz980** [comment]
Beside my quest, there is a star. It should mean I completed the quest? Anyway, the quest is not progressing after killing the mob. It says incomplete. I went to the NPC called Pyrrha who was standing at the entrance of the instance but the quest was not available to click on.
