### ISSUE TITLE
Cannot sell items until level 10

### ISSUE THREAD

**Issue by pressure68** [MATTYOneInc/AionEncomBase#2]
I know this is a minor issue, but I wanted to make note of it.

**Comment by MATTYOneInc** [comment]
The dumbest mistake in 5+ versions that I always forget about...

**Comment by MATTYOneInc** [comment]
Fix https://github.com/MATTYOneInc/AionEncomBase/commit/9b3cc42819a01f743a78c81676266cf5671a58ac
