### ISSUE TITLE
Cannot receive these quests [Elyos] -  [03076] Bolstering the Aetheric Field, [14201] Weapons of Past Destruction

### ISSUE THREAD

**Issue by ghost** [MATTYOneInc/AionEncomBase#21]
[03076] Bolstering the Aetheric Field

[14201] Weapons of Past Destruction

NPC Atropos in Theobomas have these quests but when I click on them to receive these quests, nothing happens. They are not responding.

**Comment by podpol** [comment]
[14200] Eternal Flames - fixed pls check

**Comment by benas80** [comment]
I added quest via admin, quest steps working, but i can't receive reward from quest giver(Atropos - 798155)

**Comment by pressure68** [comment]
Just tested, both quests are working fine now.
