### ISSUE TITLE
The teleporter shugo Gadarunerk is not in Inggison.- Elyos

### ISSUE THREAD

**Issue by Topaz980** [MATTYOneInc/AionEncomBase#22]
The teleporter shugo Gadarunerk is not in Inggison. Because of that, I cannot do the quest, ShuGo Go Go - 11323.

**Comment by MATTYOneInc** [comment]
check in game /movetonpc 702725

**Comment by MATTYOneInc** [comment]
<Hired Teleport Support Shugo> -->
<spawn npc_id="702725">
<spot x="1329.5541" y="281.29877" z="589.42163" h="108"/>
</spawn>

in spawns

**Comment by MATTYOneInc** [comment]
https://github.com/MATTYOneInc/AionEncomBase/commit/de8e91bd0200614c0d2d740c8fd8e7b2642a4a25

add to spawn
