### ISSUE TITLE
Izzyrunerk is missing. - Elyos.

### ISSUE THREAD

**Issue by Topaz980** [MATTYOneInc/AionEncomBase#24]
Still cannot do the quest ShuGo Go Go -11323- because the teleporter shugos are missing, apart from Gadarunerk. Gadarunerk is in Inggison Illusion Fortress now after the fix.

**Comment by MATTYOneInc** [comment]
Gadarunerk (ID: 702725) - https://ibb.co/BrGtXrF 
Should it be located somewhere else?

**Comment by MATTYOneInc** [comment]
Add Izzyrunerk https://github.com/MATTYOneInc/AionEncomBase/commit/fcc2804d9d4dc1874053abf11df7cbb412458950
