### ISSUE TITLE
Cannot open [Stamp] Luxurious Equipment Box -Elyos

### ISSUE THREAD

**Issue by Topaz980** [MATTYOneInc/AionEncomBase#25]
When double click to open it, a message comes on the screen: ''You cannot extract item while [Stamp] Luxurious Equipment box''.

**Comment by MATTYOneInc** [comment]
item id?

**Comment by podpol** [comment]
i will do) there are more of them

**Comment by pressure68** [comment]
Thank you!

**Comment by dezalmado** [comment]
It's just that no items were added to this box, but it's not just this one, there are several others, you'll see many empty boxes.
	<decomposable_select_item item_id="188058148"/>
	<decomposable_select_item item_id="188058149"/>
	<decomposable_select_item item_id="188058150"/>
	<decomposable_select_item item_id="188058151"/>
	<decomposable_select_item item_id="188058152"/>
	<decomposable_select_item item_id="188058153"/>

	---------->             <decomposable_select_item item_id="188058154"/>        <----------[Stamp] Luxurious Equipment Box

	<decomposable_select_item item_id="188058155"/>
	<decomposable_select_item item_id="188058156"/>
	<decomposable_select_item item_id="188058157"/>
	<decomposable_select_item item_id="188058158"/>
	<decomposable_select_item item_id="188058159"/>
	<decomposable_select_item item_id="188058160"/>
	<decomposable_select_item item_id="188058161"/>
	<decomposable_select_item item_id="188058162"/>
	<decomposable_select_item item_id="188058163"/>
	<decomposable_select_item item_id="188058164"/>
	<decomposable_select_item item_id="188058165"/>
	<decomposable_select_item item_id="188058166"/>
	<decomposable_select_item item_id="188058167"/>
	<decomposable_select_item item_id="188058168"/>
	<decomposable_select_item item_id="188058169"/>
	<decomposable_select_item item_id="188058170"/>
	<decomposable_select_item item_id="188058171"/>
	<decomposable_select_item item_id="188058172"/>
	<decomposable_select_item item_id="188058173"/>
	<decomposable_select_item item_id="188058174"/>
	<decomposable_select_item item_id="188058175"/>
	<decomposable_select_item item_id="188058176"/>
	<decomposable_select_item item_id="188058177"/>
	<decomposable_select_item item_id="188058178"/>
	<decomposable_select_item item_id="188058179"/>
	<decomposable_select_item item_id="188058180"/>
	<decomposable_select_item item_id="188058181"/>
	<decomposable_select_item item_id="188058182"/>
	<decomposable_select_item item_id="188058183"/>
	<decomposable_select_item item_id="188058184"/>
	<decomposable_select_item item_id="188058185"/>
	<decomposable_select_item item_id="188058186"/>
	<decomposable_select_item item_id="188058187"/>
	<decomposable_select_item item_id="188058188"/>
	<decomposable_select_item item_id="188058189"/>
	<decomposable_select_item item_id="188058190"/>
	<decomposable_select_item item_id="188058191"/>
	<decomposable_select_item item_id="188058192"/>
	<decomposable_select_item item_id="188058193"/>
	<decomposable_select_item item_id="188058194"/>
	<decomposable_select_item item_id="188058195"/>
	<decomposable_select_item item_id="188058196"/>
	<decomposable_select_item item_id="188058197"/>
	<decomposable_select_item item_id="188058198"/>

**Comment by dezalmado** [comment]
<decomposable_select_item item_id="188058154">
	    <items>
		    <item id="188058148"/>
			<item id="188058149"/>
			<item id="188058150"/>
			<item id="188058151"/>
			<item id="188058152"/>
			<item id="188058153"/>
		</items>
		</decomposable_select_item>
