### ISSUE TITLE
Quest  - Dreams of the Dungeon - 18605 - Elyos

### ISSUE THREAD

**Issue by Topaz980** [MATTYOneInc/AionEncomBase#29]
I cannot collect the reward for this quest from Ardenia. The quest is not showing up when I click on the NPC. So I cannot complete the quest.

**Comment by MATTYOneInc** [comment]
This is a quest from previous versions, there is simply no dialogue on the delivery of this quest in the client.

**Comment by podpol** [comment]
Must be fixed
